### ISSUE TITLE
Branch filtering with false-positive validation error

### ISSUE THREAD

**Issue by Vrtak-CZ** [terraform-module/terraform-aws-gitlab-oidc-provider#36]
### Steps to Reproduce:
use `project_path:mygroup/myproject:ref_type:branch:ref:*` in `repositories` variable

### Expected Result:
It works.

### Actual Result:
```
Repositories must be specified in the organization/repository format.
```

### Environment:
1.0.1 version of this module with terraform 1.4.2

### Additional Context:
[Gitlab Documentation](https://docs.gitlab.com/ee/ci/cloud_services/#configure-a-conditional-role-with-oidc-claims)

**Comment by Vrtak-CZ** [comment]
Looks like this PR can fix this issue https://github.com/terraform-module/terraform-aws-gitlab-oidc-provider/pull/34

**Comment by jbgraindorge** [comment]
Problem has not been solved, issue is still here , branch has not been merged

**Comment by banchs** [comment]
This isn't working for me. There's no way to make it work in the repositories variable. I'm always getting:

 **Repositories must be specified in the organization/repository format.**
